plugins {
    id 'java'
}

group = 'com.uket'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.security:spring-security-test'

    //spring-data
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    //database
    runtimeOnly 'com.mysql:mysql-connector-j'
    runtimeOnly 'com.h2database:h2'

    //QueryDsl
    api 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
    annotationProcessor "com.querydsl:querydsl-apt:${dependencyManagement.importedProperties['querydsl.version']}:jakarta"
    annotationProcessor "jakarta.annotation:jakarta.annotation-api"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"

    //swagger
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'

    //ticket module
    implementation project(":domain:user-domain")
    implementation project(":domain:university-domain")
    implementation project(":domain:event-domain")
    implementation project(":domain:ticket-domain")
    implementation project(":domain:terms-domain")
    implementation project(":domain:form-domain")

    //Todo: domain 모듈 전체 패키지화 완료 후 migration 삭제 필요
    implementation project(":domain:core-domain")

    implementation project(":modules:jwt-provider")
    implementation project(":modules:aws-s3")
    implementation project(":modules:slack")
    implementation project(":modules:redis")
    implementation project(":modules:qrcode-provider")
}

test {
    useJUnitPlatform()
}
