-- MySQL Script generated by MySQL Workbench
-- Tue Dec 17 20:00:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema uket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema uket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uket` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `uket` ;

-- -----------------------------------------------------
-- Table `uket`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uket`.`admin` (
  `admin_id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `is_registered` BIT(1) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uket`.`university`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uket`.`university` (
  `university_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `current_event` BIGINT NULL DEFAULT NULL,
  `email_post_fix` VARCHAR(255) NULL DEFAULT NULL,
  `logo_path` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`university_id`),
  UNIQUE INDEX `UKru212k5vib3yvu360fuy3h1g5` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uket`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uket`.`events` (
  `event_id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `modified_at` DATETIME(6) NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `university_id` BIGINT NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `deposit_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`event_id`),
  INDEX `FK3ko5bqqgrh490lyj3poc9xxxd` (`university_id` ASC) VISIBLE,
  CONSTRAINT `FK3ko5bqqgrh490lyj3poc9xxxd`
    FOREIGN KEY (`university_id`)
    REFERENCES `uket`.`university` (`university_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uket`.`banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uket`.`banner` (
  `banner_id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_id` BIGINT NULL DEFAULT NULL,
  `path` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`banner_id`),
  INDEX `FKdppoymcfgci3rb0nkgp40coff` (`event_id` ASC) VISIBLE,
  CONSTRAINT `FKdppoymcfgci3rb0nkgp40coff`
    FOREIGN KEY (`event_id`)
    REFERENCES `uket`.`events` (`event_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uket`.`shows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uket`.`shows` (
  `show_id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `modified_at` DATETIME(6) NULL DEFAULT NULL,
  `end_date` DATETIME(6) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `start_date` DATETIME(6) NULL DEFAULT NULL,
  `ticketing_date` DATETIME(6) NULL DEFAULT NULL,
  `total_ticket_count` INT NULL DEFAULT NULL,
  `event_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`show_id`),
  INDEX `FK62bhbunvyn8qgmtwgwrqsu0pn` (`event_id` ASC) VISIBLE,
  CONSTRAINT `FK62bhbunvyn8qgmtwgwrqsu0pn`
    FOREIGN KEY (`event_id`)
    REFERENCES `uket`.`events` (`event_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uket`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uket`.`reservation` (
  `reservation_id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `modified_at` DATETIME(6) NULL DEFAULT NULL,
  `end_time` DATETIME(6) NULL DEFAULT NULL,
  `reserved_count` INT NULL DEFAULT NULL,
  `start_time` DATETIME(6) NULL DEFAULT NULL,
  `total_count` INT NULL DEFAULT NULL,
  `type` ENUM('TICKETING_ALL', 'TICKETING_STUDENT') NULL DEFAULT NULL,
  `show_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`reservation_id`),
  UNIQUE INDEX `UKqiv25fjceva4udkdt8rr88tkm` (`show_id` ASC, `start_time` ASC, `end_time` ASC) VISIBLE,
  CONSTRAINT `FKnkixaet37j2pq8iqv395cdpr8`
    FOREIGN KEY (`show_id`)
    REFERENCES `uket`.`shows` (`show_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uket`.`user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uket`.`user_details` (
  `user_details_id` BIGINT NOT NULL AUTO_INCREMENT,
  `depositor_name` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` VARCHAR(255) NULL DEFAULT NULL,
  `student_code` VARCHAR(255) NULL DEFAULT NULL,
  `student_major` VARCHAR(255) NULL DEFAULT NULL,
  `university_email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`user_details_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 148
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uket`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uket`.`users` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `modified_at` DATETIME(6) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `is_registered` BIT(1) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` VARCHAR(255) NULL DEFAULT NULL,
  `platform` ENUM('KAKAO', 'GOOGLE') NULL DEFAULT NULL,
  `platform_id` VARCHAR(255) NULL DEFAULT NULL,
  `role` ENUM('ROLE_USER', 'ROLE_ADMIN') NULL DEFAULT NULL,
  `university_id` BIGINT NULL DEFAULT NULL,
  `user_details_id` BIGINT NULL DEFAULT NULL,
  `profile_image` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `UK_4ai7rrtrvwtgtqavv8okpxrul` (`user_details_id` ASC) VISIBLE,
  INDEX `FKg6bhc1g69lfy3mquw927rmr9m` (`university_id` ASC) VISIBLE,
  CONSTRAINT `FK8uj8y5ad4xl01w9wcracimb14`
    FOREIGN KEY (`user_details_id`)
    REFERENCES `uket`.`user_details` (`user_details_id`),
  CONSTRAINT `FKg6bhc1g69lfy3mquw927rmr9m`
    FOREIGN KEY (`university_id`)
    REFERENCES `uket`.`university` (`university_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uket`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uket`.`ticket` (
  `ticket_id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `modified_at` DATETIME(6) NULL DEFAULT NULL,
  `payment_at` DATETIME(6) NULL DEFAULT NULL,
  `status` ENUM('BEFORE_ENTER', 'FINISH_ENTER', 'BEFORE_PAYMENT', 'RESERVATION_CANCEL', 'EXPIRED') NULL DEFAULT NULL,
  `event_id` BIGINT NULL DEFAULT NULL,
  `reservation_id` BIGINT NULL DEFAULT NULL,
  `show_id` BIGINT NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  `ticket_no` VARCHAR(255) NULL DEFAULT NULL,
  `deleted_at` DATETIME(6) NULL DEFAULT NULL,
  `enter_at` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`ticket_id`),
  UNIQUE INDEX `UKodeus980tafqcksysjikt3gvg` (`ticket_no` ASC) VISIBLE,
  INDEX `FKpfmdrnx3oxo7d7qmkaf68pnsj` (`event_id` ASC) VISIBLE,
  INDEX `FKocy25e6lqyhj0c7bcb5auii7n` (`reservation_id` ASC) VISIBLE,
  INDEX `FKoqx6x1gm4qrcl0li6c8j9k0d7` (`show_id` ASC) VISIBLE,
  INDEX `FKmvugyjf7b45u0juyue7k3pct0` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKmvugyjf7b45u0juyue7k3pct0`
    FOREIGN KEY (`user_id`)
    REFERENCES `uket`.`users` (`user_id`),
  CONSTRAINT `FKocy25e6lqyhj0c7bcb5auii7n`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `uket`.`reservation` (`reservation_id`),
  CONSTRAINT `FKoqx6x1gm4qrcl0li6c8j9k0d7`
    FOREIGN KEY (`show_id`)
    REFERENCES `uket`.`shows` (`show_id`),
  CONSTRAINT `FKpfmdrnx3oxo7d7qmkaf68pnsj`
    FOREIGN KEY (`event_id`)
    REFERENCES `uket`.`events` (`event_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20990
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
