-- -----------------------------------------------------
-- Table `uket`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS admin (
                                     admin_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(255),
                                     is_registered BOOLEAN,
                                     name VARCHAR(255),
                                     password VARCHAR(255)
);

-- -----------------------------------------------------
-- Table `uket`.`university`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS university (
                                          university_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name VARCHAR(255),
                                          current_event BIGINT,
                                          email_post_fix VARCHAR(255),
                                          logo_path VARCHAR(255),
                                          UNIQUE (name)
);

-- -----------------------------------------------------
-- Table `uket`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS events (
                                      event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      created_at TIMESTAMP,
                                      modified_at TIMESTAMP,
                                      end_date DATE,
                                      name VARCHAR(255),
                                      start_date DATE,
                                      university_id BIGINT,
                                      location VARCHAR(255),
                                      deposit_url VARCHAR(255)

);

-- -----------------------------------------------------
-- Table `uket`.`banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS banner (
                                      banner_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      event_id BIGINT,
                                      path VARCHAR(255),
                                      title VARCHAR(255)

);

-- -----------------------------------------------------
-- Table `uket`.`shows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS shows (
                                     show_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     created_at TIMESTAMP,
                                     modified_at TIMESTAMP,
                                     end_date TIMESTAMP,
                                     location VARCHAR(255),
                                     name VARCHAR(255),
                                     start_date TIMESTAMP,
                                     ticketing_date TIMESTAMP,
                                     total_ticket_count INT,
                                     event_id BIGINT

);

-- -----------------------------------------------------
-- Table `uket`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS reservation (
                                           reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           created_at TIMESTAMP,
                                           modified_at TIMESTAMP,
                                           end_time TIMESTAMP,
                                           reserved_count INT,
                                           start_time TIMESTAMP,
                                           total_count INT,
                                           type VARCHAR(255) NOT NULL,
                                           show_id BIGINT,
                                           UNIQUE (show_id, start_time, end_time)

);

-- -----------------------------------------------------
-- Table `uket`.`user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS user_details (
                                            user_details_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            depositor_name VARCHAR(255),
                                            phone_number VARCHAR(255),
                                            student_code VARCHAR(255),
                                            student_major VARCHAR(255),
                                            university_email VARCHAR(255)
);

-- -----------------------------------------------------
-- Table `uket`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
                                     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     created_at TIMESTAMP,
                                     modified_at TIMESTAMP,
                                     email VARCHAR(255),
                                     is_registered BOOLEAN,
                                     name VARCHAR(255),
                                     phone_number VARCHAR(255),
                                     platform VARCHAR(255) NOT NULL,
                                     platform_id VARCHAR(255),
                                     role VARCHAR(255) NOT NULL,
                                     university_id BIGINT,
                                     user_details_id BIGINT,
                                     profile_image VARCHAR(1000),
                                     UNIQUE (user_details_id)

);

-- -----------------------------------------------------
-- Table `uket`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ticket (
                                      ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      created_at TIMESTAMP,
                                      modified_at TIMESTAMP,
                                      payment_at TIMESTAMP,
                                      status VARCHAR(255) NOT NULL,
                                      event_id BIGINT,
                                      reservation_id BIGINT,
                                      show_id BIGINT,
                                      user_id BIGINT,
                                      ticket_no VARCHAR(255),
                                      deleted_at TIMESTAMP,
                                      enter_at TIMESTAMP,
                                      UNIQUE (ticket_no)

);

