-- Remove depositUrl column from Events table
ALTER TABLE events DROP COLUMN deposit_url;

-- Create Account table
CREATE TABLE IF NOT EXISTS account (
                         account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         deposit_url VARCHAR(255) NOT NULL,
                         account_number VARCHAR(255),
                         account_owner VARCHAR(255),
                         ticket_price INT,
                         created_at TIMESTAMP,
                         modified_at TIMESTAMP
);

-- Add account_id column to Events table
ALTER TABLE events ADD COLUMN account_id BIGINT;
