server:
  port: 8082

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        create_empty_composites:
          enabled: true
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 100

springdoc:
  packages-to-scan: com.uket
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
---

spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      lock:
        host: localhost
        port: 6379
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uket?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DEV_MYSQL_USERNAME}
    password: ${DEV_MYSQL_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
app:
  slack:
    webhook:
      url: ${SLACK_WEBHOOK_URL}
  token:
    secret-key: testestsetsetsetsetsetsetsetsetestset
    expiration:
      ticket-expiration: 300_000
      access-token-expiration: 3_600_000
      refresh-token-expiration: 7_200_000
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/uket?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DEV_MYSQL_USERNAME}
    password: ${DEV_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: warn
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_MYSQL_URL}
    username: ${PROD_MYSQL_USERNAME}
    password: ${PROD_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    root: warn
